[package]
name = "game_protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
nalgebra = { workspace = true }
uuid = { workspace = true }
bytes = "1.10.1"

[build-dependencies]
glob = "0.3.2"
prost-build = "0.13.5"
